INSERT INTO `medicamento` (`id`, `nombre`, `concentracion`, `tipo`, `users_id`, `created_at`, `updated_at`) 
VALUES 
('249', 'INFUSOR DE PRESION   ', ' 1000ML', 'SUERO', '1', NULL, NULL),
('250', 'DEBLAX  ', 'X 1 CAP  ', 'BLANDA/VITAMINA D3', '1', NULL, NULL),
('251', 'EURYL 2 / CLONAZEPAM ', '2 MG   ', 'COMPRIMIDOS', '1', NULL, NULL),
('252', 'NOLTRON / NOREPINEFRINA ', '4MG/4ML    ', 'AMPOLLAS / IV', '1', NULL, NULL),


;